Typesafe component nesting. Parameterizes `Component` by `parent`.
```haskell
data Component parent model action
```

This PR introduces a new type variable on `Component`, and `View`. This allows
type-safe `Component` composition where the child `Component` inherit
the `model` as their `parent`. This allows children to access their
parent's `model` in a type-safe way.

The `SomeComponent` existential is now a poly-kinded singleton as well.

This means `Component` can only be nested if the parent's `model` type
aligns with the child's `parent` type.

The below typechecks because `String` on `parent`'s `model` is the
same type as the child's parent type.

```haskell
parent :: Component parent String action
child  :: Component String Int action
-- unification on parent's `model` and child's `parent` type

parent = component "test" $ \_ ->
  div_
  []
  [ "parent"
  , component_ [ id_ "child" ] child
  ]
child = component 0 $ \_ ->
  div_
  []
  [ "child"
  ]
```

The below *does not* typecheck

```haskell
parent :: Component parent String action
child :: Component (Int,Int) Int action

-- examples/components/Main.hs:606:32: error: [GHC-83865]
--     • Couldn't match type: (Int, Int)
--                      with: [Char]

parent = component "test" $ \_ ->
  div_
  []
  [ "parent"
  , component_ [ id_ "child" ] child
  ]

child = component 0 $ \_ ->
  div_
  []
  [ "child"
  ]
```

- [x] Adds some basecoat ui component library example (`miso-ui` precursor)
- [x] Bring back `App`, `startApp`, define in terms of `Component`
- [x] Add `parent` to `Component`
- [x] Adds `ComponentInfo` as `MonadReader r => r` in `Effect`.
- [x] Rearrange
- [x] Paramterize View by `model` (`View model action`)
- [x] Add `aria_` helper
- [x] Sets `parent` during procreation
- [x] Makes `update` optional
- [ ] Climb up the tree to obtain `parentComponentId` (if exists), set in `ComponentInfo`.
- [ ] Introduce `parent` function to obtain state.
- [ ] Reintroduce `notify` to `mail` `Value` to *all* children.

In order to keep `Component` generic and composable, yet type-safe,
class (like `HasField`) can be used to extract information out of the
parent's `model`, from the child.